version: "3.9"

services:
    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 5s
            retries: 5
        volumes:
            - ./data/redis:/data
    ranking_psql:
        image: postgres:17-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=ranking_psql
        volumes:
            - ./data/ranking_service_psql:/var/lib/postgresql/data
    ranking_mongod:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
            - MONGO_INITDB_DATABASE=ranking_mongod
        volumes:
            - ./data/ranking_mongod:/data/db
