version: "3.9"

services:
    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 5s
            retries: 5
        volumes:
            - ./data/redis:/data
    ranking_psql:
        image: postgres:17-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=ranking_psql
        volumes:
            - ./data/ranking_service_psql:/var/lib/postgresql/data
    ranking_mongod:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
            - MONGO_INITDB_DATABASE=ranking_mongod
        volumes:
            - ./data/ranking_mongod:/data/db
    zookeeper:
        image: docker.io/bitnami/zookeeper:3.9
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: "bitnami/kafka:latest"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        volumes:
            - ./data/kafka:/bitnami/kafka/data
