CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create ENUM type for user roles
CREATE TYPE user_role AS ENUM ('viewer', 'creator');

-- Create ENUM type for event types
CREATE TYPE event_type AS ENUM ('comment', 'react', 'share', 'view');

CREATE TABLE IF NOT EXISTS "user" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "name" VARCHAR NOT NULL,
  "avatar" VARCHAR,
  "role" user_role NOT NULL DEFAULT 'viewer',
  "updated_at" TIMESTAMP DEFAULT now(),
  "created_at" TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "video" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "title" varchar NOT NULL,
  "desc" text,
  "category_id" int NOT NULL,
  "creator_id" uuid NOT NULL,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "video" ADD FOREIGN KEY ("creator_id") REFERENCES "user" ("id");

ALTER TABLE "video" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

-- Dummy data
INSERT INTO "user" ("id","name", "role") VALUES
  ('a1b2c3d4-e5f6-4789-9012-34567890abcd','Alice Smith', 'creator'),
  ('f9e8d7c6-b5a4-4321-fedc-ba9876543210','Bob Johnson', 'viewer'),
  ('11223344-5566-4778-8990-aabbccddeeff','Charlie Brown', 'viewer'),
  ('abcdef01-2345-4678-9abc-def012345678','Diana Lee', 'creator'),
  ('98765432-10fe-4dcb-9012-34567890abcd','Eve Williams', 'viewer'),
  ('22334455-6677-4889-90aa-bbccddeeff00','Frank Miller', 'viewer');

INSERT INTO "category" ("name") VALUES
  ('Technology'),
  ('Travel'),
  ('Cooking'),
  ('Gaming'),
  ('Music');

INSERT INTO "video" ("id", "title", "desc", "category_id", "creator_id") VALUES
  ('01a2b3c4-d5e6-4f78-9012-34567890abcd', 'Introduction to Python Programming', 'Learn the basics of Python.', 1, 'a1b2c3d4-e5f6-4789-9012-34567890abcd'),
  ('98765432-10fe-4dcb-9012-34567890abcd', 'Exploring the Beaches of Bali', 'A visual journey through Balis stunning beaches.', 2, 'a1b2c3d4-e5f6-4789-9012-34567890abcd'),
  ('bcdefa01-2345-4678-9abc-def012345678', 'Delicious Homemade Pizza Recipe', 'Step-by-step guide to making perfect pizza at home.', 3, 'abcdef01-2345-4678-9abc-def012345678'),
  ('fedcba98-7654-4321-0fed-cba987654321', 'Top 10 Gaming Moments of the Year', 'Relive the most exciting moments in the gaming world.', 4, 'abcdef01-2345-4678-9abc-def012345678'),
  ('12345678-90ab-4cde-f012-34567890abcd', 'Best Indie Music Releases of 2024', 'Discover some amazing new indie artists and their tracks.', 5, 'a1b2c3d4-e5f6-4789-9012-34567890abcd'),
  ('09876543-21fe-4dcb-9012-34567890abcd', 'Advanced JavaScript Concepts', 'Dive deeper into the world of JavaScript.', 1, 'abcdef01-2345-4678-9abc-def012345678');
